# Generated by Django 5.1 on 2024-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartelaConcurso',
            fields=[
                ('id_cartela', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero_concurso', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('vencedor', models.BooleanField(default=False)),
                ('rodadas_vencedoras', models.TextField(blank=True, null=True)),
                ('vendedor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cartela_concurso',
            },
        ),
        migrations.CreateModel(
            name='Cartelas',
            fields=[
                ('id_cartela', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.BinaryField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('numeros', models.TextField(blank=True, null=True)),
                ('numero_concurso', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcursoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_concurso', models.IntegerField(unique=True)),
                ('concurso_finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NumerosSorteados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_concurso', models.IntegerField(unique=True)),
                ('drawn_numbers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
